/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gaus_rpc.h"

bool_t
xdr_Matrix (XDR *xdrs, Matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->rows))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->cols))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Solution (XDR *xdrs, Solution *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
