/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GAUS_RPC_H_RPCGEN
#define _GAUS_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Matrix {
	u_int rows;
	u_int cols;
	struct {
		u_int data_len;
		double *data_val;
	} data;
};
typedef struct Matrix Matrix;

struct Solution {
	struct {
		u_int values_len;
		double *values_val;
	} values;
};
typedef struct Solution Solution;

#define GAUSS_RPC 0x20000001
#define GAUSS_V 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOLVE_GAUSS 1
extern  Solution * solve_gauss_1(Matrix *, CLIENT *);
extern  Solution * solve_gauss_1_svc(Matrix *, struct svc_req *);
extern int gauss_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOLVE_GAUSS 1
extern  Solution * solve_gauss_1();
extern  Solution * solve_gauss_1_svc();
extern int gauss_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Matrix (XDR *, Matrix*);
extern  bool_t xdr_Solution (XDR *, Solution*);

#else /* K&R C */
extern bool_t xdr_Matrix ();
extern bool_t xdr_Solution ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GAUS_RPC_H_RPCGEN */
