/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "gaus_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Solution *
solve_gauss_1(Matrix *argp, CLIENT *clnt)
{
	static Solution clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SOLVE_GAUSS,
		(xdrproc_t) xdr_Matrix, (caddr_t) argp,
		(xdrproc_t) xdr_Solution, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
